jobs:
- name: unit-tests
  plan:
  - get: commit-queue
    trigger: true
  - task: run
    config:
      platform: linux
      image_resource:
        type: docker-image
        source:
          repository: alpine
      inputs:
      - name: commit-queue
      run:
        path: echo
        args:
          - "ran some awesome unit tests!"

- name: linting
  plan:
  - get: commit-queue
    trigger: true
  - task: run
    config:
      platform: linux
      image_resource:
        type: docker-image
        source:
          repository: alpine
      inputs:
      - name: commit-queue
      run:
        path: echo
        args:
          - "did some amazing linting!"

resource_type:
- name: git-multibranch
  type: docker-image
  source:
    repository: cfcommunity/git-multibranch-resource

resources:
- name: commit-queue
  type: git-multibranch
  source:
    uri: {{git-repo}}
    branch: .*
    private_key: {{private-repo-key}}
#
#- name: master
#  type: git-multibranch
#  source:
#    uri: {{git-repo}}
#    branch: master
#    private_key: {{private-repo-key}}