jobs:
- name: unit-tests
  plan:
  - get: commit-queue
    trigger: true
  - task: run
    config:
      platform: linux
      image_resource:
        type: docker-image
        source:
          repository: alpine
      inputs:
      - name: commit-queue
      run:
        path: echo
        args:
          - "ran some awesome unit tests!"

- name: linting
  plan:
  - get: commit-queue
    trigger: true
  - task: run
    config:
      platform: linux
      image_resource:
        type: docker-image
        source:
          repository: alpine
      inputs:
      - name: commit-queue
      run:
        path: echo
        args:
          - "did some amazing linting!"

- name: confirm-commit
  plan:
  - get: commit-queue
    trigger: true
    passed:
      - unit-tests
      - linting
  - task: run
    config:
      platform: linux
      image_resource:
        type: docker-image
        source:
          repository: node
      inputs:
      - name: commit-queue
      run:
        path: node
        args:
          - -v
  - put: git

resources:
  - name: commit-queue
    type: git
    source:
      uri: {{push-repo}}
      branch: develop
      private_key: {{private-repo-key}}

  - name: git
    type: git
    source:
      uri: {{fetch-repo}}
      branch: develop
      private_key: {{private-repo-key}}