#!/usr/bin/env bash

AGE=`printenv branch-age`
REGEX=`printenv branch-regex`

# For Testing
AGE="1 hour ago"
REGEX="master-pending-\d"

git config remote.origin.fetch "+refs/heads/*:refs/remotes/origin/*"
git fetch origin
git remote update origin --prune

for BRANCH in $(git branch -r | sed /\*/d); do
    if [ -z "`git log -1 --after="${AGE}" -s ${BRANCH}`" ] && [ ! -z "`echo ${BRANCH} | grep ${REGEX}`" ]; then
        BRANCH_NAME=`echo ${BRANCH} | sed 's/.*\/\(.*\)/\1/'`

        git push origin :${BRANCH_NAME}
    fi
done