#!/usr/bin/env bash

set -e

SSH_KEY=`printenv private-repo-key`
GIT_REPO=`git remote -v | grep fetch | head -n 1 | awk '{print $$2}' | sed 's/.*@\(.*\):.*/\1/'`

touch ~/.ssh/id_rsa
echo "${SSH_KEY}" > ~/.ssh/id_rsa
chmod 600 ~/.ssh/id_rsa

eval "$(ssh-agent -s)"
ssh-add
ssh-keyscan ${GIT_REPO} >> ~/.ssh/known_hosts