#!/usr/bin/env bash

set -e

THEN_RUN=$1

SSH_KEY=`printenv private-repo-key`

touch ~/.ssh/id_rsa
echo "${SSH_KEY}" > ~/.ssh/id_rsa
chmod 600 ~/.ssh/id_rsa

eval "$(ssh-agent -s)"
ssh-add
ssh-keyscan github.com >> ~/.ssh/known_hosts

if [[ ${THEN_RUN} != "" ]]
then
    PROJECT_ROOT=`git rev-parse --show-toplevel`

    eval "bash ${PROJECT_ROOT}/ci/scripts/${THEN_RUN}"
fi
