#!/usr/bin/env bash

set -e

SLACK_CHANNEL=`printenv slack-channel`
BUILD_RESULT=`printenv build-result`

GIT_WEB_URL=`git remote -v | grep fetch | head -n 1 | sed 's/.*@\(.*\):\(.*\)\..*/https:\/\/\1\/\2\//'`

TARGET_BRANCH=`printenv target-branch`
CURRENT_BRANCH=`git branch | grep pending | awk '{print $1}'`

git config remote.origin.fetch "+refs/heads/*:refs/remotes/origin/*"
# Not sure we need these lines, delete them if it still works
git fetch origin
#git checkout ${TARGET_BRANCH}

if [[ ${BUILD_RESULT} == "success" ]]
then
    MESSAGE="Successfully pushed into <${GIT_WEB_URL}/tree/${TARGET_BRANCH}|'origin/${TARGET_BRANCH}'>"
    COLOR="36a64f"
else
    MESSAGE="Failed to push <${GIT_WEB_URL}/tree/${CURRENT_BRANCH}|'${CURRENT_BRANCH}'> into <${GIT_WEB_URL}/tree/${TARGET_BRANCH}|'origin/${TARGET_BRANCH}'>"
    COLOR="ff0000"
fi

COMMITS=`git log --pretty=format:"%ct %H %ae %s" origin/${TARGET_BRANCH}..${CURRENT_BRANCH} \
            | awk '{ print "{" }
                   { print "    \"color\": \"#'${COLOR}'\"," }
                   { print "    \"ts\": \"" $1 "\"," }
                   { print "    \"author_name\": \"" $3 "\"," }
                   { print "    \"title_link\": \"'${GIT_WEB_URL}'/commit/" $2 "\"," }
      { $1=$2=$3=""; print "    \"title\": \""$0"\"" }
                   { print "    \"is_app_unfurl\": false" }
                   { print "}," }'`

PAYLOAD="payload={
    \"text\": \"${MESSAGE}\",
    \"channel\": \"${SLACK_CHANNEL}\",
    \"username\": \"commit-bot\",
    \"icon_emoji\": \":robot_face:\",
    \"attachments\": [
        ${COMMITS%?}
    ]
}"

PROJECT_ROOT=`git rev-parse --show-toplevel`

echo "Slack message generated: "
echo
echo "${PAYLOAD}"
echo
echo

echo "${PAYLOAD}" > ${PROJECT_ROOT}/../slack-payload/payload.json