#!/usr/bin/env bash

AGE=`printenv branch-age`
REGEX=`printenv branch-regex`
COLOR=`printenv color`
OUTPUT=`printenv output`

GIT_WEB_URL=`git remote -v | grep push | head -n 1 | sed 's/.*@\(.*\):\(.*\)\..*/https:\/\/\1\/\2/'`

git config remote.origin.fetch "+refs/heads/*:refs/remotes/origin/*"
git fetch origin
git remote update origin --prune

for BRANCH in $(git branch | sed /\*/d); do
    if [ -n "`git log -1 --before="${AGE}" -s $BRANCH`" ] && [ -n "`echo ${BRANCH} | grep "${REGEX}"`" ]; then
        BRANCHES+=`git log -1 --pretty=format:"%cr" -s ${BRANCH} \
            | awk '{ print "{" }
                   { print "    \"color\": \"'${COLOUR}'\"," }
                   { print "    \"title_link\": \"'${GIT_WEB_URL}'/tree/'${BRANCH}'""\"," }
                   { print "    \"title\": \"'${BRANCH}'""\"," }
                   { print "    \"text\": \""Last updated $0"\"" }
                   { print "}," }'`
    fi
done

PAYLOAD="[
    ${BRANCHES%?}
]"

PROJECT_ROOT=`git rev-parse --show-toplevel`

echo "Slack attachment generated: "
echo
echo "${PAYLOAD}"
echo

echo "${PAYLOAD}" > ${PROJECT_ROOT}/../slack-payload/${OUTPUT}