#!/usr/bin/env bash

set -e

SLACK_CHANNEL=`printenv slack-channel`
BUILD_RESULT=`printenv build-result`

CURRENT_BRANCH=`git branch | grep pending | awk '{print $1}'`

git config remote.origin.fetch "+refs/heads/*:refs/remotes/origin/*"
git fetch origin
git checkout master

if [[ ${BUILD_RESULT} == "success" ]]
then
    COMMITS=`git log --pretty=format:"%ct %ae %s" master..${CURRENT_BRANCH} \
            | awk '{ print "{" }
                   { print "    \"color\": \"#36a64f\"," }
                   { print "    \"ts\": \"" $1 "\"," }
                   { print "    \"author_name\": \"" $2 "\"," }
         { $1=$2=""; print "    \"title\": \"" $0 "\"" }
                   { print "}," }'`

    PAYLOAD="payload={
        'text': \"Successfully pushed into 'origin/master'\",
        'channel': '$SLACK_CHANNEL',
        'username': 'commit-bot',
        'icon_emoji': ':robot_face:',
        'attachments': [
            ${COMMITS%?}
        ]
    }"
else
    COMMITS=`git log --pretty=format:"%ct %ae %s" master..${CURRENT_BRANCH} \
            | awk '{ print "{" }
                   { print "    \"color\": \"#ff0000\"," }
                   { print "    \"ts\": \"" $1 "\"," }
                   { print "    \"author_name\": \"" $2 "\"," }
         { $1=$2=""; print "    \"title\": \"" $0 "\"" }
                   { print "}," }'`

    PAYLOAD="payload={
        'text': \"Failed to push `${CURRENT_BRANCH}` into 'origin/master'\",
        'channel': '$SLACK_CHANNEL',
        'username': 'commit-bot',
        'icon_emoji': ':robot_face:',
        'attachments': [
            ${COMMITS%?}
        ]
    }"
fi

PROJECT_ROOT=`git rev-parse --show-toplevel`

echo "${PAYLOAD}" > ${PROJECT_ROOT}/../slack-payload/payload.json