#!/usr/bin/env bash

set -e

GIT_REPO=`git remote -v | grep fetch | head -n 1 | sed 's/.*:\(.*\)\..*/\1/'`
GIT_WEB_URL=`git remote -v | grep push | head -n 1 | sed 's/.*@\(.*\):\(.*\)\..*/https:\/\/\1\/\2/'`

TARGET_BRANCH=`printenv target-branch`
CURRENT_BRANCH=`git branch | grep pending | awk '{print $1}'`

git config remote.origin.fetch "+refs/heads/*:refs/remotes/origin/*"
git fetch origin

COMMITS=`git log --pretty=format:"%ct %H %ae %s" origin/${TARGET_BRANCH}..${CURRENT_BRANCH} \
            | awk '{ print "{" }
                   { print "    \"color\": \"#f49542\"," }
                   { print "    \"ts\": \"" $1 "\"," }
                   { print "    \"footer\": \"By " $3 "\"," }
                   { print "    \"title_link\": \"'${GIT_WEB_URL}'/commit/" $2 "\"," }
      { $1=$2=$3=""; print "    \"title\": \""$0"\"" }
                   { print "}," }'`

PAYLOAD="[
    {
        \"color\": \"#307fff\",
        \"title\": \"'<${GIT_WEB_URL}/tree/${CURRENT_BRANCH}|${CURRENT_BRANCH}>' into '<${GIT_WEB_URL}/tree/${TARGET_BRANCH}|${TARGET_BRANCH}>'\"
    },
    ${COMMITS%?}
]"

PROJECT_ROOT=`git rev-parse --show-toplevel`

echo "Slack attachment generated: "
echo
echo "${PAYLOAD}"
echo

echo "${PAYLOAD}" > ${PROJECT_ROOT}/../slack-payload/commits.json