#!/usr/bin/env bash

AGE=`printenv branch-age`
REGEX=`printenv branch-regex`
COLOR=`printenv color`
OUTPUT=`printenv output`

# For Testing
#AGE="1 hour ago"
#REGEX="master-pending-\d"
#COLOR=""

GIT_WEB_URL=`git remote -v | grep push | head -n 1 | sed 's/.*@\(.*\):\(.*\)\..*/https:\/\/\1\/\2/'`

git config remote.origin.fetch "+refs/heads/*:refs/remotes/origin/*"
git fetch origin
git remote update origin --prune

for BRANCH in $(git branch -r | sed /\*/d); do
    if [ -z "`git log -1 --after="${AGE}" -s ${BRANCH}`" ] && [ ! -z "`echo ${BRANCH} | grep ${REGEX}`" ]; then
        BRANCH_NAME=`echo ${BRANCH} | sed 's/.*\/\(.*\)/\1/'`

        BRANCHES+=`git log -1 --pretty=format:"%ct %H %ae %s" -s ${BRANCH} \
            | awk '{ print "{" }
                   { print "    \"color\": \"'${COLOR}'\"," }
                   { print "    \"title_link\": \"'${GIT_WEB_URL}'/tree/'${BRANCH_NAME}'""\"," }
                   { print "    \"title\": \"'${BRANCH_NAME}'""\"," }
                   { print "    \"footer\": \"By " $3 " \"," }
                   { print "    \"ts\": \"" $1 "\"," }
      { $1=$2=$3=""; print "    \"text\": \"" $0"\"" }
                   { print "}," }'`
    fi
done

PAYLOAD="[
    ${BRANCHES%?}
]"

PROJECT_ROOT=`git rev-parse --show-toplevel`

echo "Slack attachment generated: "
echo
echo "${PAYLOAD}"
echo

echo "${PAYLOAD}" > ${PROJECT_ROOT}/../slack-payload/${OUTPUT}