#!/usr/bin/env bash

set -e

#BUILD_RESULT=`printenv build-result`

GIT_REPO=`git remote -v | grep fetch | head -n 1 | sed 's/.*:\(.*\)\..*/\1/'`
GIT_WEB_URL=`git remote -v | grep push | head -n 1 | sed 's/.*@\(.*\):\(.*\)\..*/https:\/\/\1\/\2/'`

TARGET_BRANCH=`printenv target-branch`
CURRENT_BRANCH=`git branch | grep pending | awk '{print $1}'`

git config remote.origin.fetch "+refs/heads/*:refs/remotes/origin/*"
git fetch origin

#if [[ ${BUILD_RESULT} == "success" ]]
#then
#    MESSAGE="Successfully pushed into <${GIT_WEB_URL}/tree/${TARGET_BRANCH}|'origin/${TARGET_BRANCH}'>"
#    COLOR="36a64f"
#else
#    MESSAGE="Failed to push <${GIT_WEB_URL}/tree/${CURRENT_BRANCH}|'${CURRENT_BRANCH}'> into <${GIT_WEB_URL}/tree/${TARGET_BRANCH}|'origin/${TARGET_BRANCH}'>"
#    COLOR="ff0000"
#fi

COMMITS=`git log --pretty=format:"%ct %H %ae %s" origin/${TARGET_BRANCH}..${CURRENT_BRANCH} \
            | awk '{ print "{" }
                   { print "    \"color\": \"#f49542\"," }
                   { print "    \"ts\": \"" $1 "\"," }
                   { print "    \"author_name\": \"" $3 "\"," }
                   { print "    \"title_link\": \"'${GIT_WEB_URL}'/commit/" $2 "\"," }
      { $1=$2=$3=""; print "    \"title\": \""$0"\"" }
                   { print "}," }'`

PAYLOAD="[
    {
        \"title\": \"<${GIT_WEB_URL}/tree/${CURRENT_BRANCH}|'${CURRENT_BRANCH}'>   :arrow_right: :arrow_right: :arrow_right:   <${GIT_WEB_URL}/tree/${TARGET_BRANCH}|'origin/${TARGET_BRANCH}'>\"
    },
    ${COMMITS%?}
]"

PROJECT_ROOT=`git rev-parse --show-toplevel`

echo "Slack message generated: "
echo
echo "${PAYLOAD}"
echo

echo "${PAYLOAD}" > ${PROJECT_ROOT}/../slack-payload/payload.json