---

platform: linux

image_resource:
  type: docker-image
  source:
    repository: governmentpaas/git-ssh

inputs:
- name: commit-queue

run:
  dir: commit-queue/scripts
  path: eval
  args:
    - "setup-ssh && cleanup-branch"
