---

platform: linux

image_resource:
  type: docker-image
  source:
    repository: governmentpaas/git-ssh

inputs:
- name: commit-queue

run:
  dir: commit-queue
  path: scripts/setup-ssh-and
  args: [ cleanup-branch ]
