---

platform: linux

image_resource:
  type: docker-image
  source:
    repository: governmentpaas/git-ssh

inputs:
- name: branch

run:
  dir: branch
  path: sh
  args:
  - -exc
  - |
    ci/scripts/setup-ssh
    ci/scripts/cleanup-branch
