---

platform: linux

image_resource:
  type: docker-image
  source:
    repository: governmentpaas/git-ssh

inputs:
- name: branch

run:
  dir: branch
  path: ci/scripts/setup-ssh-and
  args: [ cleanup-branch ]
