---

# A task that just fails, can be useful to test failure states in your
# pipeline!

platform: linux

image_resource:
  type: docker-image
  source:
    repository: alpine

inputs:
- name: pending

run:
  path: sh
  args:
  - -exc
  - |
    exit 1