---

platform: linux
image_resource:
  type: docker-image
  source:
    repository: governmentpaas/git-ssh

inputs:
- name: commit-queue

outputs:
- name: slack-payload

run:
  path: scripts/slack-notification-generate
  dir: commit-queue
#  args:
#    - {{private-repo-key}}
#    - {{slack-channel}}
#    - success
