#!/usr/bin/env bash

set -e

SSH_KEY=$1

CURRENT_BRANCH=`git branch | grep pending | awk '{print $1}'`

touch key
echo SSH_KEY > ssh-key

eval `ssh-agent -s`
ssh-add -K ssh-key

git push origin --delete ${CURRENT_BRANCH}