#!/usr/bin/env bash

CURRENT_BRANCH=`git branch | grep \* | awk '{print $2}'`
TIMESTAMP=`date +%s`

PENDING_BRANCH=${CURRENT_BRANCH}-pending-${TIMESTAMP}

echo $TIMESTAMP

git pull --rebase
git checkout -b ${PENDING_BRANCH}
git push --set-upstream origin ${PENDING_BRANCH}
git checkout ${CURRENT_BRANCH}