#!/usr/bin/env bash

set -e

SSH_KEY=`printenv private-repo-key`

touch ~/.ssh/id_rsa
echo "${SSH_KEY}" > ~/.ssh/id_rsa
chmod 600 ~/.ssh/id_rsa

eval "$(ssh-agent -s)"
ssh-add
ssh-keyscan github.com >> ~/.ssh/known_hosts
