#!/usr/bin/env bash

set -e

SLACK_URL=`printenv slack-url`
PROJECT_ROOT=`git rev-parse --show-toplevel`

PAYLOAD=`cat ${PROJECT_ROOT}/../slack-payload/payload.json`

curl -X POST --data-urlencode "${PAYLOAD}" ${SLACK_URL}