#!/usr/bin/env bash

set -e

SSH_KEY=$1

echo "${SSH_KEY}" > ~/.ssh/id_rsa
chmod 600 ~/.ssh/id_rsa

eval "$(ssh-agent -s)"
ssh-add
ssh-keyscan github.com >> ~/.ssh/known_hosts

#------------------------------------------------------------#

SLACK_URL=$2
SLACK_CHANNEL=$3

RESULT=$4

CURRENT_BRANCH=`git branch | grep pending | awk '{print $1}'`

git config remote.origin.fetch "+refs/heads/*:refs/remotes/origin/*"
git fetch origin

if [[ ${RESULT} == "success" ]]
then
    COMMITS=`git log --pretty=format:"%ct %ae %s" origin/master..${CURRENT_BRANCH} \
            | awk '{ print "{" }
                   { print "    \"color\": \"#36a64f\"," }
                   { print "    \"ts\": \"" $1 "\"," }
                   { print "    \"author_name\": \"" $2 "\"," }
         { $1=$2=""; print "    \"title\": \"" $0 "\"" }
                   { print "}," }'`

    PAYLOAD="payload={
        'text': \"Successfully pushed into 'origin/master'\",
        'channel': '$SLACK_CHANNEL',
        'username': 'commit-bot',
        'icon_emoji': ':robot_face:',
        'attachments': [
            ${COMMITS%?}
        ]
    }"
else
    COMMITS=`git log --pretty=format:"%ct %ae %s" origin/master..master \
            | awk '{ print "{" }
                   { print "    \"color\": \"#ff0000\"," }
                   { print "    \"ts\": \"" $1 "\"," }
                   { print "    \"author_name\": \"" $2 "\"," }
         { $1=$2=""; print "    \"title\": \"" $0 "\"" }
                   { print "}," }'`

    PAYLOAD="payload={
        'text': \"Failed to push `${CURRENT_BRANCH}` into 'origin/master'\",
        'channel': '$SLACK_CHANNEL',
        'username': 'commit-bot',
        'icon_emoji': ':robot_face:',
        'attachments': [
            ${COMMITS%?}
        ]
    }"
fi

echo "${PAYLOAD}"

curl -X POST --data-urlencode "${PAYLOAD}" ${SLACK_URL}