jobs:
- name: hello-world
  plan:
  - get: commit-queue
    trigger: true
  - task: hello-world
    file: commit-queue/ci/tasks/placeholder.yml

resources:
- name: commit-queue
  type: git
  source:
    uri: {{git-repo}}
    branches: master
    private_key: {{private-repo-key}}