jobs:
- name: validate-commits
  plan:
  - get: commit-queue
    trigger: true
  - aggregate:
    - task: unit-tests
      file: commit-queue/ci/tasks/unit-tests.yml
    - task: linting
      file: commit-queue/ci/tasks/linting.yml

- name: merge-to-master
  plan:
  - get: commit-queue
    trigger: true
    passed: [ validate-commits ]
  - task: run
    file: commit-queue/ci/tasks/slack-notification-generate.yml
    params:
      priate-repo-key: {{private-repo-key}}
      slack-channel: {{slack-channel}}
      build-status: success
  - put: master
    params:
      repository: commit-queue
  - task: run
    config:
      platform: linux
      image_resource:
        type: docker-image
        source:
          repository: governmentpaas/git-ssh
      inputs:
      - name: slack-payload
      - name: commit-queue
      run:
        path: scripts/slack-notification-send
        args:
          - {{slack-url}}
        dir: commit-queue

- name: cleanup-branch
  plan:
  - get: commit-queue
    trigger: true
    passed: [ merge-to-master ]
  - task: run
    config:
      platform: linux
      image_resource:
        type: docker-image
        source:
          repository: governmentpaas/git-ssh
      inputs:
      - name: commit-queue
      run:
        path: scripts/cleanup-branch
        args:
          - {{private-repo-key}}
        dir: commit-queue

resources:
- name: commit-queue
  type: git-multibranch
  source:
    uri: {{git-repo}}
    branches: .*-pending-\d*
    private_key: {{private-repo-key}}

- name: master
  type: git-multibranch
  source:
    uri: {{git-repo}}
    branch: master
    private_key: {{private-repo-key}}

resource_types:
- name: git-multibranch
  type: docker-image
  source:
    repository: cfcommunity/git-multibranch-resource
    tag: latest
