jobs:
- name: unit-tests
  plan:
  - get: commit-queue
    trigger: true
  - task: run
    config:
      platform: linux
      image_resource:
        type: docker-image
        source:
          repository: alpine
      inputs:
      - name: commit-queue
      run:
        path: echo
        args:
          - "ran some awesome unit tests!"

- name: linting
  plan:
  - get: commit-queue
    trigger: true
  - task: run
    config:
      platform: linux
      image_resource:
        type: docker-image
        source:
          repository: alpine
      inputs:
      - name: commit-queue
      run:
        path: echo
        args:
          - "did some amazing linting!"

- name: merge-to-master
  plan:
  - get: commit-queue
    trigger: true
    passed: [ unit-tests, linting ]
  - put: master
    params:
      repository: commit-queue
  - put: slack
    params:
      username: {{slack-username}}
      channel: {{slack-channel}}
      icon_url: {{slack-icon-url}}
      text: "Successfully pushed into 'origin/master'"
      attachments:
      - color: "#36a64f"
        text: "Adding Slack config for successful build"
      - color: "#36a64f"
        text: "Script to write Slack message"

- name: cleanup-branch
  plan:
  - get: commit-queue
    trigger: true
    passed: [ merge-to-master ]
  - task: run
    config:
      platform: linux
      image_resource:
        type: docker-image
        source:
          repository: governmentpaas/git-ssh
      inputs:
      - name: commit-queue
      run:
        path: scripts/cleanup-branch
        args:
          - {{private-repo-key}}
        dir: commit-queue

resources:
- name: commit-queue
  type: git-multibranch
  source:
    uri: {{git-repo}}
    branches: .*-pending-\d*
    private_key: {{private-repo-key}}

- name: master
  type: git-multibranch
  source:
    uri: {{git-repo}}
    branch: master
    private_key: {{private-repo-key}}

- name: slack
  type: slack-notification
  source:
    url: {{slack-url}}

resource_types:
- name: git-multibranch
  type: docker-image
  source:
    repository: cfcommunity/git-multibranch-resource
    tag: latest

- name: slack-notification
  type: docker-image
  source:
    repository: cfcommunity/slack-notification-resource
    tag: latest
