jobs:
- name: validate-commits
  plan:
  - get: commit-queue
    trigger: true
  - aggregate:
    - task: unit-tests
      file: commit-queue/ci/tasks/unit-tests.yml
      on_failure:
        do:
        - task: generate-slack-message
          file: commit-queue/ci/tasks/slack-generate.yml
          params:
            private-repo-key: {{private-repo-key}}
            slack-channel: {{slack-channel}}
            build-result: failure
        - task: run
          file: commit-queue/ci/tasks/slack-send.yml
          params:
            slack-url: {{slack-url}}
    - task: linting
      file: commit-queue/ci/tasks/linting.yml
      on_failure:
        do:
        - task: generate-slack-message
          file: commit-queue/ci/tasks/slack-generate.yml
          params:
            private-repo-key: {{private-repo-key}}
            slack-channel: {{slack-channel}}
            build-result: failure
        - task: run
          file: commit-queue/ci/tasks/slack-send.yml
          params:
            slack-url: {{slack-url}}




- name: merge-to-master
  plan:
  - get: commit-queue
    trigger: true
    passed: [ validate-commits ]
  - task: generate-slack-message
    file: commit-queue/ci/tasks/slack-generate.yml
    params:
      private-repo-key: {{private-repo-key}}
      slack-channel: {{slack-channel}}
      build-result: success
  - put: master
    params:
      repository: commit-queue
  - task: run
    file: commit-queue/ci/tasks/slack-send.yml
    params:
      slack-url: {{slack-url}}

- name: cleanup-branch
  plan:
  - get: commit-queue
    trigger: true
    passed: [ merge-to-master ]
  - task: run
    file: commit-queue/ci/tasks/cleanup-branch.yml
    params:
      private-repo-key: {{private-repo-key}}

resources:
- name: commit-queue
  type: git-multibranch
  source:
    uri: {{git-repo}}
    branches: .*-pending-\d*
    private_key: {{private-repo-key}}

- name: master
  type: git-multibranch
  source:
    uri: {{git-repo}}
    branch: master
    private_key: {{private-repo-key}}

resource_types:
- name: git-multibranch
  type: docker-image
  source:
    repository: cfcommunity/git-multibranch-resource
    tag: latest
