jobs:
- name: validation
  plan:
  - get: pending
    trigger: true
  - task: generate-slack-message
    file: pending/ci/tasks/slack-commits.yml
    params:
      private-repo-key: ((private-repo-key))
      target-branch: "master"
  - put: slack
    params:
      username: ((project-name))
      icon_url: ((slack-image))
      text: |
          *<((concourse-url))/teams/$BUILD_TEAM_NAME/pipelines/$BUILD_PIPELINE_NAME/jobs/$BUILD_JOB_NAME/builds/$BUILD_NAME|Validating pending commits...>*
      attachments_file: slack-payload/commits.json
  - aggregate:
    - task: unit-tests
      file: pending/ci/tasks/placeholder.yml
    - task: linting
      file: pending/ci/tasks/placeholder.yml
#    Uncomment below to test your failure state
#    - task: fail
#      file: pending/ci/tasks/fail.yml
  on_failure:
    put: slack
    params:
      username: ((project-name))
      icon_url: ((slack-image))
      attachments:
      - color: "#ff0000"
        title: Push failed!
        text: <((concourse-url))/teams/$BUILD_TEAM_NAME/pipelines/$BUILD_PIPELINE_NAME/jobs/$BUILD_JOB_NAME/builds/$BUILD_NAME|Validation failure...>

- name: merge-commits
  plan:
  - get: pending
    trigger: true
    passed: [ validation ]
  - put: master
    params:
      repository: pending
  - put: slack
    params:
      username: ((project-name))
      icon_url: ((slack-image))
      attachments:
      - color: "#36a64f"
        title: Push succeeded!
  on_failure:
    put: slack
    params:
      username: ((project-name))
      icon_url: ((slack-image))
      attachments:
      - color: "#ff0000"
        title: Push failed!
        text: <((concourse-url))/teams/$BUILD_TEAM_NAME/pipelines/$BUILD_PIPELINE_NAME/jobs/$BUILD_JOB_NAME/builds/$BUILD_NAME|Merge failure...>

- name: cleanup-pending
  plan:
  - get: pending
    trigger: true
    passed: [ merge-commits ]
  - task: run
    file: pending/ci/tasks/cleanup-branch.yml
    params:
      private-repo-key: {{private-repo-key}}

- name: cleanup-branches
  plan:
  - get: master
  - task: test
    params:
      private-repo-key: ((private-repo-key))
    config:
      platform: linux

      image_resource:
        type: docker-image
        source:
          repository: governmentpaas/git-ssh

      inputs:
      - name: master

      run:
        dir: master
        path: sh
        args:
        - -exc
        - |
          ci/scripts/setup-ssh
          git config remote.origin.fetch "+refs/heads/*:refs/remotes/origin/*"
          git fetch origin
          git branch --all
  - task: run
    file: master/ci/tasks/slack-old-branches.yml
    params:
      branch-age: "1 hour ago"
      branch-regex: ((pending-branches))
      color: "#f49542"
      output: "warning.json"
      private-repo-key: ((private-repo-key))
  - put: slack
    params:
      username: ((project-name))
      icon_url: ((slack-image))
      text: |
          *The following branches will be deleted tomorrow...*
      attachments_file: slack-payload/warning.json

resources:
- name: pending
  type: git-multibranch
  source:
    uri: ((git-repo))
    branches: ((pending-branches))
    private_key: ((private-repo-key))


- name: master
  type: git-multibranch
  source:
    uri: ((git-repo))
    branch: master
    private_key: ((private-repo-key))

- name: slack
  type: slack-notification
  source:
    url: ((slack-url))

resource_types:
- name: git-multibranch
  type: docker-image
  source:
    repository: cfcommunity/git-multibranch-resource
    tag: latest

- name: slack-notification
  type: docker-image
  source:
    repository: cfcommunity/slack-notification-resource
    tag: latest
