jobs:
- name: validation
  plan:
  - get: pending
    trigger: true
  - task: generate-slack-message
    file: pending/ci/tasks/slack-generate.yml
    params:
      private-repo-key: ((private-repo-key))
      target-branch: ((main-branch))
  - put: slack
    params:
      username: ((project-name))
      icon_url: ((slack-image))
      text: |
          <((concourse-url))/teams/$BUILD_TEAM_NAME/pipelines/$BUILD_PIPELINE_NAME/jobs/$BUILD_JOB_NAME/builds/$BUILD_NAME|Validating pending commits...>
      attachments_file: slack-payload/payload.json
  - aggregate:
    - task: unit-tests
      file: pending/ci/tasks/placeholder.yml
    - task: linting
      file: pending/ci/tasks/placeholder.yml
  on_failure:
    do:
    - put: slack
      params:
        username: ((project-name))
        icon_url: ((slack-image))
        text: FAILED

- name: merge-commits
  plan:
  - get: pending
    trigger: true
    passed: [ validation ]
  - task: generate-slack-message
    file: pending/ci/tasks/slack-generate.yml
    params:
      private-repo-key: ((private-repo-key))
      build-result: success
      target-branch: ((main-branch))
  - put: ((project-name))
    params:
      repository: pending
  - put: slack
    params:
      username: ((project-name))
      icon_url: ((slack-image))
      text: SUCCESS

#- name: cleanup-branch
#  plan:
#  - get: pending
#    trigger: true
#    passed: [ merge-commits ]
#  - task: run
#    file: pending/ci/tasks/cleanup-branch.yml
#    params:
#      private-repo-key: ((private-repo-key))

resources:
- name: pending
  type: git-multibranch
  source:
    uri: ((git-repo))
    branches: .*-pending-\d*
    private_key: ((private-repo-key))


- name: ((project-name))
  type: git-multibranch
  source:
    uri: ((git-repo))
    branch: ((main-branch))
    private_key: ((private-repo-key))

- name: slack
  type: slack-notification
  source:
    url: ((slack-url))

resource_types:
- name: git-multibranch
  type: docker-image
  source:
    repository: cfcommunity/git-multibranch-resource
    tag: latest

- name: slack-notification
  type: docker-image
  source:
    repository: cfcommunity/slack-notification-resource
    tag: latest
